export const PLAYBACK_CONTROL_PLAY = 'PLAYBACK_CONTROL_PLAY';
export const PLAYBACK_CONTROL_PAUSE = 'PLAYBACK_CONTROL_PAUSE';
export const PLAYBACK_CONTROL_STEP_FORWARD = 'PLAYBACK_CONTROL_STEP_FORWARD';
export const PLAYBACK_CONTROL_STEP_BACKWARD = 'PLAYBACK_CONTROL_STEP_BACKWARD';
